### ISSUE TITLE
打卡

### ISSUE THREAD

**Issue by Lhamber** [chillsoul/EzCheckInSchool#6]
早上打卡失败，好几天来第一次

**Comment by chillsoul** [comment]
我看了你Actions的[运行结果](https://github.com/Lhamber/EzCheckInSchool/runs/1152025237)，原因是完美校园服务器崩了，这个暂时无解。

现在的逻辑是打卡失败尝试10次，最长300秒，如果300秒内都没有恢复，那就进行到下一个人了。所以目前最好是更改打卡时间到一个打的人少的时间点，其他诸如延长等待时间或是增加尝试次数也可以尝试。

**Comment by 2939748214** [comment]
为什么添加信息的时候会显示“Failed to add secret. Please try again.”

**Comment by chillsoul** [comment]
> 为什么添加信息的时候会显示“Failed to add secret. Please try again.”

请更换浏览器
